title = "Rafael Abbariao"
baseURL = "https://rafaelabbariao.netlify.app"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "New York, NY"
email = "rafael.abbariao@gmail.com"
favicon = "/favicon.ico"
firstName = "Rafael Carlos"
lastName = "Abbariao"
phone = "19174366516"
profileImage = "img/Raf2025.jpg"
showBlog = true
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = false
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "G-JDVXRKSRK8"

[[params.handles]]
link = "https://www.linkedin.com/in/rafael-abbariao/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/rafaelcarlosabbariao"
name = "GitHub"

[[params.handles]]
link = "https://medium.com/@rafaelabbariao"
name = "Medium"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
